base_url: '/'
title: 'The Organge+'
theme: 'bookworm'

# post excerpt
summaryLength: 20

# google analytics
google_analytics: "UA-40665301-3" # example : UA-123-45
# disqus short name
disqus_shortname: "" # get your shortname form here : https://disqus.com


############################## Plugins ##############################
# CSS Plugins
params:
  plugins:
    css:
      - "plugins/bootstrap/bootstrap.min.css"
      - "css/style.css"
      - "https://fonts.googleapis.com/css2?family=Mulish:wght@400;600;700&display=swap"
    js:
      - "plugins/jquery/jquery.min.js"
      - "plugins/bootstrap/bootstrap.min.js"
      - "plugins/search/fuse.min.js"
      - "plugins/search/mark.js"
      - "plugins/search/search.js"
      - "https://unpkg.com/eva-icons"

#################### default parameters ################################

  logo: "images/logo.png"
  logo_height: "35px"
  favicon: "images/favicon.png"
  # Meta data
  description: "Drinking orange juice is good for your health. Reading some orange code is good too :D"
  author: "Dung Nguyen"
  # contact form action
  contact_form_action: "#" # contact form works with https://formspree.io
  # search
  search: true
  # main section
  mainSections: ["blog"]
  # copyright
  copyright: "Blog by Dung Nguyen.Theme by [Gethugothemes](https://gethugothemes.com/)"

  # sidebar
  sidebar: false

# Preloader
  preloader:
    enable: false
    preloader: "" # use jpg, png, svg or gif format.


# Subscription
  subscription:
    enable: false
    # mailchimp subsciption
    mailchimp_form_action: "#" # replace this url with yours
    mailchimp_form_name: "#" # replace this code with yours
    title: "Subscribe for our monthly newsletter."
    input_placeholder: "Enter your email" 

# cookies
  cookies:
    enable: false
    expire_days: 2


############################# Main Menu ########################
menus:
  main:
    - weight: 1
      url: "/"
      name: "Blog"


    - weight: 2
      url: "tags/"
      name: "Tags"

    - weight: 3
      url: "about"
      name: "About me"


    - weight: 2
      url: "#"
      name: "More"
      has_children: true
      children:

       - weight: 3
         url: "categories/"
         name: "Category"

       - weight: 4
         url: "elements/"
         name: "Elements"

       - weight: 5
         url: "privacy/"
         name: "Privacy"

       - weight: 6
         url: "terms-conditions/"
         name: "Terms & Conditions"

############################# Footer Menu ########################
  footer:
    - weight: 1
      url: "about/"
      name: "About me"


    - weight: 2
      url: "author/"
      name: "Authors"
